version: '3.9'

services:

  web:
    build: ./docker
    container_name: apache_php

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./web:/var/www/html

    depends_on:
      - db

    networks:
      - internal_net

  db:
    image: mysql:8.0
    container_name: mysql_db

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sito
      MYSQL_USER: user
      MYSQL_PASSWORD: password

    ports:
      - "3306:3306"

    volumes:
      - db_data:/var/lib/mysql

    networks:
      - internal_net

volumes:
  db_data:

networks:
  internal_net:
    driver: bridge